### Importanto o NumPy

In [2]:
# Importando o NumPy
import numpy as np

# Primeiras impressões

In [5]:
a = np.array([10, 20, 30, 40])

In [6]:
type(a)

numpy.ndarray

In [8]:
# Criando matrizes 2 x 2
matriz = np.array([[1,2], [3,4]])

In [9]:
# Acessando o elemento "4"
print(matriz[1][1])
print(matriz[-1][-1])

4
4


In [10]:
# Acessando elementos da segunda linha
matriz[1,:]

array([3, 4])

In [11]:
# Acessando elementos da primeiro coluna
matriz[:,0]

array([1, 3])

In [12]:
# Acessando a matriz transposta
# Transforma linhas em colunas
matriz.transpose()

array([[1, 3],
       [2, 4]])

In [15]:
# Soma de Matrizes
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [16]:
# Subratração de Matrizes
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [17]:
# Multiplicação de Matrizes
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [18]:
# Somando os elementos de um Array
m3 = np.array([1,2,3,4])
m3.sum()

10

In [19]:
# Descobrindo o índice do maior valor em uma array
m3.argmax()

3

In [20]:
# O índice do menor valor do array
m3.argmin()

0

# Ilustrando Eficiência do NumPy

In [21]:
import time

In [22]:
soma = 0

inicio = time.time()
for i in range(1, 10000000):
    soma += i
fim = time.time()
print(fim - inicio)

1.0209989547729492


In [24]:
inicio = time.time()
np.arange(1, 10000000).sum()
fim = time.time()
print(fim - inicio)

0.0199887752532959


# Slices Array

In [26]:
# Exemplo com lista

l = [20, 30, 10, 40]

# Inicia do elemento na posição 1, e vai até a posição 3 não incluso.
print(l[1:3])

# Não determinamos o ínicio, nem o fim, mas estabelecemos o passo em valor 2
print(l[::2])

[30, 10]
[20, 10]


In [27]:
# Exemplo com NumPy

a = np.array(l)

print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [32]:
# Copiando a lista L para a nova variável L2
l2 = l[:]

# Alterando o primeiro elemento de L2
l2[0] = 1000

# Verificando os valores
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [36]:
# Copiando o Array A para a variável B
b = a[:]

# Alterando o primeiro valor de B
b[0] = 1000

# Verificando os valores em Array Numpy
print("Array A: {}".format(a))
print("Array B: {}".format(b))

Array A: [1000   42   42   42]
Array B: [1000   42   42   42]
Array A: [42 42 42 42]


In [39]:
# Alterando todos os valores de B
b[:] = 42
print("Array A: {}".format(a))

Array A: [42 42 42 42]


In [41]:
# Como copiar Array no NumPy - Utilizando a Função Copy

c = a.copy()

# Imprimindo as cópias
print("Array A: {}".format(a))
print("Array C: {}".format(c))

Array A: [42 42 42 42]
Array C: [42 42 42 42]


In [40]:
# Realizando as alterações
c[0] = 10000
print("Array A: {}".format(a))
print("Array C: {}".format(c))

Array A: [42 42 42 42]
Array C: [10000    42    42    42]


# Matrizes

In [44]:
# Matriz é uma lista de listas

matriz = [[5,4,7], [0,3,4], [0,0,6]]

for linha in matriz:
    print(linha)

[5, 4, 7]
[0, 3, 4]
[0, 0, 6]


### Matrizes com NumPy

In [46]:
# Imaginemos uma lista de pontos por jogador de basquete

joao_pts = [20, 30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
marcos_pts = [12, 34, 12, 43]

# Criando a Matriz com Numpy
pontos = np.array([joao_pts, pedro_pts, maria_pts, marcos_pts])

In [49]:
# Imprimir os pontos
print(pontos)

# Imprimir os pontos do João
print(pontos[0])

# Imprimir o valor 100 (segunda linha e primeira coluna)
print(pontos[1][0])

[[ 20  30  40  15]
 [100  24  48  23]
 [ 92  22  34  12]
 [ 12  34  12  43]]
[20 30 40 15]
100


In [50]:
# Criando um Array de 20 valores (0 à 19)
my_data = np.arange(0,20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [52]:
# Transformando o my_data em uma Matriz 5x4
mat1 = np.reshape(my_data, (5,4))
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### Operações de Matrizes

### Coletando valores de um arquivo TXT

In [3]:
# coletando valores de um arquivo

val1, val2, val3 = np.loadtxt("./original/dados.txt", skiprows=1, unpack=True)
print(val1)
print(val2)
print(val3)

[0.1212 0.104  0.5661 0.762 ]
[0.842    0.5422   0.932    0.847361]
[0.3672  0.34551 0.2344  0.1538 ]


In [4]:
my_array = np.genfromtxt("./original/dados2.txt", skip_header=1, filling_values=1000)
print(my_array)

[[1.21200e-01 8.42000e-01 3.67200e-01]
 [1.00000e+03 5.42200e-01 3.45510e-01]
 [5.66100e-01 9.32000e-01 1.00000e+03]
 [7.62000e-01 8.47361e-01 1.53800e-01]]


### Coletando valores de um arquivo CSV

In [10]:
valores = np.genfromtxt("./original/arquivo.csv", delimiter=",", skip_header=1)
valores

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.],
       [34., 54., 23.]])

### Analisando o Iris DataSet

In [22]:
iris_data = np.genfromtxt('./original/iris.data', delimiter=',', usecols=(0,1,2,3))
print(iris_data)
len(iris_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [23]:
iris_data[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [15]:
iris_data[:50,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ])